export type {
  TipoEstrutura,
  Dispositivo,
  VersaoArtigo,
  Artigo,
  NodoEstrutura,
  Legislacao,
  LegislacaoMeta,
} from "./types";

import type { LegislacaoMeta } from "./types";

export const LEGISLACOES: LegislacaoMeta[] = [
  {
    id: "codigo-penal",
    nome: "Codigo Penal",
    nomeAbreviado: "CP",
    referencia: "DL 2.848/1940",
    fonte: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#ef4444",
  },
  {
    id: "cpp",
    nome: "Codigo de Processo Penal",
    nomeAbreviado: "CPP",
    referencia: "DL 3.689/1941",
    fonte: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#f97316",
  },
  {
    id: "lep",
    nome: "Lei de Execucao Penal",
    nomeAbreviado: "LEP",
    referencia: "L 7.210/1984",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l7210compilado.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#8b5cf6",
  },
  {
    id: "maria-da-penha",
    nome: "Lei Maria da Penha",
    nomeAbreviado: "LMP",
    referencia: "L 11.340/2006",
    fonte: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11340.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#ec4899",
  },
  {
    id: "drogas",
    nome: "Lei de Drogas",
    nomeAbreviado: "LD",
    referencia: "L 11.343/2006",
    fonte: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11343.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#14b8a6",
  },
  {
    id: "eca",
    nome: "Estatuto da Crianca e do Adolescente",
    nomeAbreviado: "ECA",
    referencia: "L 8.069/1990",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l8069compilado.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#06b6d4",
  },
  {
    id: "abuso-autoridade",
    nome: "Lei de Abuso de Autoridade",
    nomeAbreviado: "LAA",
    referencia: "L 13.869/2019",
    fonte: "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/lei/L13869.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#f59e0b",
  },
  {
    id: "cf88-titulo2",
    nome: "Constituição Federal (Trechos Selecionados)",
    nomeAbreviado: "CF",
    referencia: "CF/1988 - Dir. Fundamentais, Judiciário, MP, Defensoria, Família",
    fonte: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#22c55e",
  },
  {
    id: "contravencoes",
    nome: "Lei das Contravencoes Penais",
    nomeAbreviado: "LCP",
    referencia: "DL 3.688/1941",
    fonte: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3688.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#a3a3a3",
  },
  {
    id: "desarmamento",
    nome: "Estatuto do Desarmamento",
    nomeAbreviado: "ED",
    referencia: "L 10.826/2003",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/2003/l10.826.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#64748b",
  },
  {
    id: "testemunhas-protegidas",
    nome: "Lei de Protecao a Testemunhas",
    nomeAbreviado: "LPT",
    referencia: "L 9.807/1999",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l9807.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#6366f1",
  },
  {
    id: "prisao-temporaria",
    nome: "Lei da Prisao Temporaria",
    nomeAbreviado: "LPTe",
    referencia: "L 7.960/1989",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l7960.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#dc2626",
  },
  {
    id: "mariana-ferrer",
    nome: "Lei Mariana Ferrer",
    nomeAbreviado: "LMF",
    referencia: "L 14.245/2021",
    fonte: "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/L14245.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#d946ef",
  },
  {
    id: "lc80",
    nome: "Lei Organica da Defensoria Publica",
    nomeAbreviado: "LC80",
    referencia: "LC 80/1994",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/lcp/Lcp80.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#059669",
  },
  {
    id: "lce26-bahia",
    nome: "Lei Complementar Estadual da Defensoria Publica da Bahia",
    nomeAbreviado: "LCE26",
    referencia: "LCE 26/2006",
    fonte: "https://al.ba.gov.br/atividade-legislativa/legislacao/pesquisa-legislativa",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#0284c7",
  },
  {
    id: "jecrim",
    nome: "Lei dos Juizados Especiais Criminais",
    nomeAbreviado: "JECRIM",
    referencia: "L 9.099/1995",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l9099.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#10b981",
  },
  {
    id: "crimes-hediondos",
    nome: "Lei dos Crimes Hediondos",
    nomeAbreviado: "LCH",
    referencia: "L 8.072/1990",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l8072compilado.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#dc2626",
  },
  {
    id: "interceptacao",
    nome: "Lei de Interceptação Telefônica",
    nomeAbreviado: "LIT",
    referencia: "L 9.296/1996",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l9296.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#7c3aed",
  },
  {
    id: "organizacao-criminosa",
    nome: "Lei de Organização Criminosa",
    nomeAbreviado: "LORC",
    referencia: "L 12.850/2013",
    fonte: "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12850.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#1d4ed8",
  },
  {
    id: "ctb-crimes",
    nome: "Código de Trânsito Brasileiro — Crimes",
    nomeAbreviado: "CTB",
    referencia: "L 9.503/1997 — Cap. XIX",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#d97706",
  },
  {
    id: "tortura",
    nome: "Lei de Tortura",
    nomeAbreviado: "LT",
    referencia: "L 9.455/1997",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l9455.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#991b1b",
  },
  {
    id: "racismo",
    nome: "Lei do Racismo e Discriminação",
    nomeAbreviado: "LR",
    referencia: "L 7.716/1989",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l7716.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#065f46",
  },
  {
    id: "crimes-ambientais",
    nome: "Lei de Crimes Ambientais",
    nomeAbreviado: "LCA",
    referencia: "L 9.605/1998",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#15803d",
  },
  {
    id: "estatuto-idoso",
    nome: "Estatuto do Idoso — Capítulo Penal",
    nomeAbreviado: "EI",
    referencia: "L 10.741/2003",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/2003/l10.741.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#0369a1",
  },
  {
    id: "lavagem-dinheiro",
    nome: "Lei de Lavagem de Dinheiro",
    nomeAbreviado: "LLD",
    referencia: "L 9.613/1998",
    fonte: "https://www.planalto.gov.br/ccivil_03/leis/l9613.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#6b21a8",
  },
  {
    id: "identificacao-criminal",
    nome: "Lei de Identificação Criminal",
    nomeAbreviado: "LIC",
    referencia: "L 12.037/2009",
    fonte: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2009/lei/l12037.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#0f766e",
  },
  {
    id: "crimes-ciberneticos",
    nome: "Lei de Crimes Cibernéticos",
    nomeAbreviado: "LCC",
    referencia: "L 12.737/2012 + L 14.155/2021",
    fonte: "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/lei/l12737.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#1e40af",
  },
  {
    id: "antiterrorismo",
    nome: "Lei Antiterrorismo",
    nomeAbreviado: "LAT",
    referencia: "L 13.260/2016",
    fonte: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/lei/l13260.htm",
    dataUltimaAtualizacao: "",
    totalArtigos: 0,
    cor: "#7f1d1d",
  },
];
